export declare class BuildDirConst {
    static readonly HVIGOR_COMPILE: string;
    static readonly BUILD_ROOT: string;
    static readonly PREVIEW_BUILD_PATH: string;
    static readonly TEST_BUILD_PATH: string;
    static readonly INTERMEDIATES: string;
    static readonly GENERATED: string;
    static readonly BUILD_OUTPUTS: string;
    static readonly INTERMEDIATES_ORIGINAL_RES: string;
    static readonly INTERMEDIATES_MERGE_RES: string;
    static readonly INTERMEDIATES_MERGE_PROFILE: string;
    static readonly INTERMEDIATES_PROCESS_PROFILE: string;
    static readonly LEGACY_MANIFEST: string;
    static readonly INTERMEDIATES_JS: string;
    static readonly INTERMEDIATES_RES: string;
    static readonly INTERMEDIATES_RES_DEDUPLICATE: string;
    static readonly RESTOOL_BUILD_RESOURCES: string;
    static readonly RAW_FILE: string;
    static readonly ARK_DATA: string;
    static readonly SCHEMA: string;
    static readonly UTD: string;
    static readonly LITE_SOURCES: string;
    static readonly LOADER_OUT: string;
    static readonly LOADER_OUT_LITE: string;
    static readonly JS_BUILD_ASSETS: string;
    static readonly LOADER: string;
    static readonly HAR_DUPLICATE: string;
    static readonly ID_DEFINED: string;
    static readonly BUILD_CACHE: string;
    static readonly CPP_OUTPUT: string;
    static readonly LIBS: string;
    static readonly BINXO: string;
    static readonly STRIPPED_NATIVE_LIBS = "stripped_native_libs";
    static readonly PATCH = "patch";
    static readonly SHELL: string;
    static readonly SRC: string;
    static readonly MAIN: string;
    static readonly MOCK: string;
    static readonly RESOURCES: string;
    static readonly SYSCAP: string;
    static readonly BASE: string;
    static readonly PROFILE: string;
    static readonly R: string;
    static readonly CMAKE: string;
    static readonly BUILD_INFO: string;
    static readonly OBJ: string;
    static readonly APP_COMPILED: string;
    static readonly MODULE_COMPILED: string;
    static readonly HAR_COMPILED: string;
    static readonly IDS_MAP: string;
    static readonly TEMP_DIR: string;
    static readonly PM_DIR: string;
    static readonly HAP_METADATA = "hap_metadata";
    static readonly HSP_METADATA = "hsp_metadata";
    static readonly TRANSFORM_LIB = "transformLib";
    static readonly REMOTE_HSP = "remote_hsp";
    static readonly INTERMEDIATES_ROUTER_MAP_TEMP_DIR: string;
    static readonly INTERMEDIATES_SHARE_CONFIG_TEMP_DIR: string;
    static readonly INTERMEDIATES_STARTUP_TEMP_DIR: string;
    static readonly DEFAULT_STARTUP_CONFIG_FILE_NAME: string;
    static readonly RESOURCES_BASE_PROFILE_DIR: string;
    static readonly BASE_PROFILE_DIR: string;
    static readonly SRC_MAIN: string;
    static readonly CPP_TYPES: string;
    static readonly INTEGRATED_HSP = "integrated_hsp";
    static readonly MAPPING = "mapping";
    static readonly PACKAGE_HAP = "package";
    static readonly DECLARE_FILE_OUTPUT = "etsFortgz";
    static readonly RESOURCE_STR = "resource_str";
    static readonly SOURCEMAP_INTERMEDIATE_DIR: string;
    static readonly OUTPUT_SYMBOL: string;
    static readonly PACKAGE_APP: string;
    static readonly FAST_APP_DIR: string;
    static readonly PAC_DIR: string;
    static readonly PRELOAD: string;
    static readonly META_INF: string;
}
export declare class BuildArtifactConst {
    static readonly CONFIG_JSON: string;
    static readonly RESOURCE_INDEX: string;
    static readonly MERGE_RES_FILE_INDEX: string;
    static readonly RESOURCE_TABLE_H: string;
    static readonly RESOURCE_TABLE_TS: string;
    static readonly RESOURCE_TABLE_TXT: string;
    static readonly LEGACY_MANIFEST_JSON: string;
    static readonly ID_DEFINED_JSON: string;
    static readonly PACK_INFO: string;
    static readonly PACK_RES: string;
    static readonly RELEASE_MAP: string;
    static readonly LOADER_JSON: string;
    static readonly SOURCE_HAR_DUPLICATE_FILES_INFO: string;
    static readonly BYTE_CODE_HAR_DUPLICATE_FILES_INFO: string;
    static readonly HAR_DUPLICATE_INFO: string;
    static readonly PKG_CONTEXT_INFO_DUPLICATE_INFO: string;
    static readonly RESOURCES_DUPLICATE_INFO: string;
    static readonly ROUTER_MAP_DUPLICATE_INFO: string;
    static readonly LOADER_ROUTER_MAP_DUPLICATE_INFO: string;
    static readonly START_UP_DUPLICATE_INFO: string;
    static readonly ABILITY_DUPLICATE_INFO: string;
    static readonly SO_DUPLICATE_INFO: string;
    static readonly WIDGET_LOADER_JSON: string;
    static readonly INSIGHT_INTENT_JSON: string;
    static readonly FORM_CONFIG_JSON: string;
    static readonly PREVIEW_BUILD_PARAM_JSON: string;
    static readonly OUTPUT_METADATA_JSON: string;
    static readonly PROFILE_DIR: string;
    static readonly BUILD_PROFILE_FILE: string;
    static readonly MODULE_INFO_FILE: string;
    static readonly MODULE_JSON5: string;
    static readonly MOCK_CONFIG_JSON5: string;
    static readonly MAIN_PAGES_JSON: string;
    static readonly BASE_NATIVE_LIBS_JSON: string;
    static readonly BINXO_NATIVE_LIBS_JSON: string;
    static readonly INDEX_JS: string;
    static readonly INDEX_ETS: string;
    static readonly INTEGRATED_HSP_CACHE: string;
    static readonly SOURCEMAPS_MAP: string;
    static readonly DEFAULT_ROUTER_MAP: string;
    static readonly TEMP_ROUTER_MAP_FILE_NAME: string;
    static readonly LOADER_ROUTER_MAP_FILE_NAME: string;
    static readonly DEFAULT_SHARE_CONFIG: string;
    static readonly TEMP_SHARE_CONFIG_FILE_NAME: string;
    static readonly LOADER_SHARE_CONFIG_FILE_NAME: string;
    static readonly MODULES_ABC: string;
    static readonly NAME_CACHE: string;
    static readonly BYTE_CODE_OBF_CONFIG = "config.json";
    static readonly APP_SYMBOL: string;
    static readonly MOCK_CONFIG_JSON: string;
    static readonly PRELOAD_SO_FILE_NAME: string;
}
export declare class BuildArtifactExtension {
    static readonly DOT_HAP: string;
    static readonly DOT_BIN: string;
    static readonly DOT_APP: string;
    static readonly DOT_HSP: string;
    static readonly DOT_TGZ: string;
    static readonly DOT_ZIP: string;
}
export declare class ResToolInputTypeConst {
    static readonly APP: string;
    static readonly MODULE: string;
    static readonly HAR: string;
}
